// #include "RecoParticleFlow/PFClusterTools/interface/PFEnergyCalibration.h"
// #include "CondFormats/PhysicsToolsObjects/interface/PerformancePayloadFromTFormula.h"
// #include "PerformancePayloadFromTFormula.h" // already in .h

// #include "CondFormats/ESObjects/interface/ESEEIntercalibConstants.h"

#include <TMath.h>
#include <cmath>
#include <vector>
#include <map>
#include <algorithm>
#include <numeric>
#include <array>

#include "TH1D.h"
#include "TF1.h"

using namespace std;

bool debug = false;

TH1D *heta(0);
TF1 *pfec_f1hh(0), *pfec_f1he(0);
PFEnergyCalibration::PFEnergyCalibration() {

  // Functions needed to invert response when true energy not given
  pfec_f1hh = new TF1("f1hh","max([3],[0]*(1-[1]*pow(x,[2]-1)))*x",
		      0.,5000.);
  pfec_f1he = new TF1("f1he",
		      "max([3],[0]*(1-[1]*pow(x,[2]-1)))*(1-[8])*x+"
		      "max([7],[4]*(1-[5]*pow(x,[6]-1)))*[8]*x",
		      0.,5000.);

// Array auto-generated by pfhc/drawPionGun.C
// Hadron response |eta| bins
  const int neta = 29;
  double veta[neta+1] =
    {0.000, 0.087, 0.174, 0.261, 0.348, 0.435, 0.522, 0.609, 0.696, 0.783,
     0.879, 0.957, 1.044, 1.131, 1.218, 1.305, 1.392, 1.479, 1.566, 1.653,
     1.740, 1.830, 1.930, 2.043, 2.172, 2.322, 2.500, 2.650, 2.853, 2.964};
  
  // Histogram to make finding |eta| bin easier
  heta = new TH1D("heta",";|#eta|;", neta, &veta[0]);

} // PFEnergyCalibration

// Text file containing the H and EH response arrays
// Eventually something to go into database, but can select suitable one here
//#include "piongun_Winter25.txt"
//#include "piongun_Winter25_v3.txt"
//#include "piongun_Winter24_v9v10.txt"
//#include "piongun_Winter25v2NoPu.txt"
//#include "piongun_PFHC26v1.txt"
#include "piongun_PFHC26v4.txt"
void PFEnergyCalibration::energyEmHad(double t, double& e, double& h, double eta, double phi) const {

  // Save input energies in const form
  const double tt = t;
  const double ee = e;
  const double hh = h;

  // True pT from true energy
  double pt = tt / cosh(eta);
  
  // Retrieve parameters of H, E-of-EH and H-of-EH for given abseta bin
  double abseta = fabs(eta);
  const int neta = heta->GetNbinsX();
  int ieta = heta->GetXaxis()->FindBin(abseta);
  ieta = max(1,min(neta,ieta))-1;

  // These arrays are defined in #included piongun.txt just before function call
  array<double, 4>& phh = vhh[ieta]; // H-of-H (H hadrons)
  array<double, 4>& peh = veh[ieta]; // H-of-EH (EH hadron)
  array<double, 4>& pee = vee[ieta]; // E-of-EH (EH hadrons)
  
  // Calculate raw ECAL fraction to decide H vs EH and to calculate EH
  const double fe = (ee+hh>0 ? ee / (ee + hh) : 0.);

  // If true energy is not given, invert response function(s) to get true pT
  // Use TF1::GetX, which internally uses Brent Root Finder
  // https://root.cern.ch/doc/master/classTF1.html#aaa11403e909bf42f0d04356ede442763
  if (!(tt>0)) {

    // Set precision, Npx, maxiter, logx low to make this very fast
    const double eps  = 1e-3; // 0.1% precision for true pT is enough (1E-10)
    const int maxiter = 100; // (100)
    const bool logx = true; // (false)
    const int npx = 4; // must be [4,1e6] (100)
    const double k = 1.05; // extend root finder range by 5% to avoid errors
    double ptc = (ee+hh)/cosh(eta);
    
    // H-hadron with single power law
    pfec_f1hh->SetParameters(phh[0],phh[1],phh[2],phh[3]);
    double ptmin_hh = (ptc/phh[0])/k; // [0]=c=R(pT->inf)
    double ptmax_hh = (ptc/phh[3])*k; // [3]=Rmin=R(pT->0)
    pfec_f1hh->SetNpx(npx);
    double pt_hh = pfec_f1hh->GetX(ptc, ptmin_hh, ptmax_hh, eps, maxiter, logx);

    // EH-hadron with two power laws weighted by f_ECAL
    pfec_f1he->SetParameters(peh[0],peh[1],peh[2],peh[3],
    			     pee[0],pee[1],pee[2],pee[3], fe);
    double p0 = (1-fe)*peh[0] + fe*pee[0];
    double p3 = (1-fe)*peh[3] + fe*pee[3];
    double ptmin_eh = (ptc/p0)/k; // [0]=c=R(pT->inf)
    double ptmax_eh = (ptc/p3)*k; // [3]=Rmin=R(pT->0)
    pfec_f1he->SetNpx(npx);
    double pt_eh = pfec_f1he->GetX(ptc, ptmin_eh, ptmax_eh, eps, maxiter, logx);

    // Use raw ECAL fraction to decide correct case to apply
    if (fe<0.01) { // Clear H hadron
      pt = pt_hh;
    }
    else if (fe>0.1) { // Clear EH hadron
      pt = pt_eh;
    }
    else { // Transition region between the two
      double x = (fe-0.01)/(0.1-0.01);
      pt = (1-x) * pt_hh + x * pt_eh;
    }
  } // !(tt>0)
  
  // Calculate responses for H hadrons and for E,H components of HE
  // Response limits at low end are important to stabilize behavior
  double rh =  max(phh[3], phh[0]*(1 - phh[1]*pow(pt, phh[2]-1)));
  double reh = max(peh[3], peh[0]*(1 - peh[1]*pow(pt, peh[2]-1)));
  double ree = max(pee[3], pee[0]*(1 - pee[1]*pow(pt, pee[2]-1)));
  double re = reh*(1-fe) + ree*fe;
  
  // Calculate total corrected energies under both H and EH hypotheses
  double ehh = (hh + ee) / rh;
  double ehe = (hh + ee) / re;

  // Re-distribute EH correction to ECAL and HCAL components
  // Example case: ree=reh => we=fe
  // Example case: fe=0 => we=0, fe=1 => we=1
  double we = (fe/ree) / (fe/ree + (1-fe)/reh);

  // Same for H hadrons, assuming ree=1 (for MIPs)
  // Example case: rh=ree=1 => wh=(1-fe)
  // Example case: fe=0 => wh=1, fe=1 => wh=0
  double wh = (1-fe)/rh / (fe + (1-fe)/rh);
  
  // Use raw ECAL fraction to decide correct case to apply
  if (fe<0.01) { // Clear H hadron
    e = ehh * (1-wh);
    h = ehh * wh;
  }
  else if (fe>0.1) { // Clear EH hadron
    e = ehe * we;
    h = ehe * (1-we);
  }
  else { // Transition region between the two
    double x = (fe-0.01)/(0.1-0.01);
    e = (1-x) * (ehh * (1-wh)) + x * (ehe * we);
    h = (1-x) * (ehh * wh) + x * (ehe * (1-we));
  }

  if (debug) {
    cout << "PFEnergyCalibrationFromMikko.cc:" << endl;
    cout << " tt = " << tt
	 << " hh = " << hh
      	 << " ee = " << ee
	 << " eta = " << eta
      	 << " phi = " << phi << endl
	 << " ieta = " << ieta
      	 << " neta = " << neta
	 << " (etamin=" << heta->GetBinLowEdge(ieta+1) << ","
      	 << " etamid=" << heta->GetBinCenter(ieta+1) << ","
      	 << " etamax=" << heta->GetBinLowEdge(ieta+2) << ")" << endl
      	 << " h = " << h
      	 << " e = " << e
	 << " corr = " << (e+h)/(ee+hh)
	 << endl << flush;
  }
  
  return;
} // energyEmHad

